"""Public Google Sheets contract for the supplier register."""

from __future__ import annotations

HEADERS: dict[str, list[str]] = {
    "SUPPLIERS": [
        "SUPPLIER_ID", "COMPANY_NAME", "LEGAL_NAME", "SHORT_NAME", "INN", "KPP", "OGRN",
        "SUPPLIER_TYPE", "MANUFACTURER", "DISTRIBUTOR", "DEALER", "WEBSITE", "DOMAIN",
        "CITY", "REGION", "ADDRESS", "CATEGORY_L1", "CATEGORY_L2", "CATEGORY_L3",
        "CATEGORY_L4", "BRANDS", "PRIMARY_EMAIL", "PRIMARY_PHONE", "FIRST_CONTACT_DATE",
        "LAST_CONTACT_DATE", "TOTAL_THREADS", "TOTAL_RFQ", "TOTAL_QUOTES", "TOTAL_REFUSALS",
        "RFQ_SENT", "RFQ_REPLIED", "RESPONSE_RATE", "AVG_RESPONSE_TIME_HOURS",
        "LAST_RESPONSE_DATE", "LAST_QUOTE_DATE", "LAST_RFQ_ID", "LAST_TENDER_ID",
        "SOURCE_MAILBOXES", "ENTITY_ROLE", "CONFIDENCE", "REVIEW_STATUS", "CREATED_AT", "UPDATED_AT",
    ],
    "CONTACTS": [
        "CONTACT_ID", "SUPPLIER_ID", "FULL_NAME", "FIRST_NAME", "LAST_NAME", "PATRONYMIC",
        "POSITION", "EMAIL", "PHONE", "PHONE_EXT", "TELEGRAM", "WHATSAPP", "IS_PRIMARY",
        "FIRST_SEEN_AT", "LAST_SEEN_AT", "SOURCE_MESSAGE_ID", "SOURCE_THREAD_ID", "ACTIVE", "CONFIDENCE",
    ],
    "SUPPLIER_CATEGORIES": [
        "SUPPLIER_ID", "CATEGORY_L1", "CATEGORY_L2", "CATEGORY_L3", "CATEGORY_L4",
        "CONFIDENCE", "FIRST_SEEN_AT", "LAST_SEEN_AT", "SOURCE_THREAD_ID", "SOURCE_MESSAGE_ID",
    ],
    "CATEGORY_FILTER": [
        "FILTER_GROUP", "CATEGORY_L1", "CATEGORY_L2", "CATEGORY_L3", "CATEGORY_L4",
        "COMPANY_NAME", "SUPPLIER_ID", "BRANDS", "PRIMARY_EMAIL", "PRIMARY_PHONE",
        "LAST_CONTACT_DATE", "TOTAL_RFQ", "TOTAL_QUOTES", "SOURCE_THREAD_ID",
        "SOURCE_MESSAGE_ID", "CONFIDENCE", "REVIEW_STATUS",
    ],
    "SUPPLIER_PRODUCTS": [
        "SUPPLIER_ID", "BRAND", "MANUFACTURER", "MODEL", "ARTICLE", "PRODUCT_NAME",
        "CATEGORY_L1", "CATEGORY_L2", "CATEGORY_L3", "CATEGORY_L4", "FIRST_SEEN_AT",
        "LAST_SEEN_AT", "RFQ_ID", "TENDER_ID", "THREAD_ID", "SOURCE_MESSAGE_ID", "CONFIDENCE",
    ],
    "QUOTES": [
        "QUOTE_ID", "SUPPLIER_ID", "GMAIL_ACCOUNT", "THREAD_ID", "MESSAGE_ID", "TENDER_ID", "RFQ_ID",
        "QUOTE_NUMBER", "QUOTE_DATE", "QUOTE_VALID_UNTIL", "PRODUCT_NAME", "BRAND", "MODEL", "ARTICLE",
        "QUANTITY", "UNIT", "PRICE_UNIT", "PRICE_TOTAL", "CURRENCY", "VAT_RATE", "VAT_INCLUDED",
        "WITHOUT_VAT", "DISCOUNT_PERCENT", "DISCOUNT_AMOUNT", "AVAILABILITY", "PRODUCTION_DAYS",
        "DELIVERY_DAYS", "DELIVERY_CITY", "DELIVERY_COST", "DELIVERY_INCLUDED", "PAYMENT_TERMS",
        "PREPAYMENT_PERCENT", "WARRANTY", "COUNTRY_ORIGIN", "MANUFACTURER", "ATTACHMENT_FILENAME",
        "ATTACHMENT_TYPE", "CREATED_AT",
    ],
    "INTERACTIONS": [
        "INTERACTION_ID", "SUPPLIER_ID", "GMAIL_ACCOUNT", "THREAD_ID", "MESSAGE_ID", "TENDER_ID",
        "RFQ_ID", "DATE", "DIRECTION", "FROM_EMAIL", "TO_EMAIL", "SUBJECT", "MESSAGE_TYPE",
        "RESPONSE_TYPE", "REFUSAL_REASON", "HAS_ATTACHMENT", "SHORT_SUMMARY", "PROCESSED_AT",
    ],
    "ALIASES": [
        "SUPPLIER_ID", "ALIAS_TYPE", "ALIAS_VALUE", "DOMAIN", "EMAIL", "PHONE", "COMPANY_NAME",
        "INN", "WEBSITE", "CONFIDENCE",
    ],
    "REVIEW_QUEUE": [
        "REVIEW_ID", "TYPE", "SUPPLIER_CANDIDATE_1", "SUPPLIER_CANDIDATE_2", "VALUE",
        "REASON", "MESSAGE_ID", "THREAD_ID", "CONFIDENCE", "STATUS",
    ],
    "PROCESSING_LOG": [
        "RUN_ID", "STARTED_AT", "FINISHED_AT", "MAILBOX", "MESSAGES_FOUND", "MESSAGES_PROCESSED",
        "SUPPLIERS_CREATED", "SUPPLIERS_UPDATED", "CONTACTS_CREATED", "QUOTES_CREATED",
        "ERROR_COUNT", "STATUS", "ERROR_TEXT",
    ],
    "ATTACHMENTS": [
        "GMAIL_ACCOUNT", "MESSAGE_ID", "ATTACHMENT_ID", "FILENAME", "MIME_TYPE", "FILE_SIZE",
        "PARSE_ERROR",
    ],
    "DASHBOARD": ["METRIC", "VALUE", "DETAIL"],
}

REVIEW_STATUSES = ["NEW", "IN_REVIEW", "CONFIRMED", "REJECTED", "MERGED"]


def column_letter(index: int) -> str:
    """Convert one-based column index into A1 notation."""
    value = ""
    while index:
        index, digit = divmod(index - 1, 26)
        value = chr(65 + digit) + value
    return value
